# Generated by Django 5.2.1 on 2025-05-16 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='codigo_os',
            field=models.CharField(default=uuid.uuid4, max_length=12, unique=True),
        ),
    ]
